# Generated by Django 5.2.17 on 2026-09-25 20:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=32, unique=True)),
                ("marker", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identity", models.CharField(max_length=700, unique=True)),
                ("organisation", models.CharField(max_length=400)),
                ("department", models.CharField(blank=True, max_length=400)),
                ("ministry", models.CharField(blank=True, max_length=400)),
                ("state", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["organisation", "department"],
                "indexes": [
                    models.Index(fields=["ministry"], name="buyer_ministry_idx"),
                    models.Index(fields=["state"], name="buyer_state_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("marker_before", models.JSONField(blank=True, default=dict)),
                ("marker_after", models.JSONField(blank=True, default=dict)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"], name="crawlrun_source_started_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("cppp", "CPPP"), ("gem", "GeM"), ("tntenders", "Tamil Nadu")],
                        max_length=32,
                    ),
                ),
                ("source_key", models.CharField(max_length=200)),
                ("feed", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("reference_number", models.CharField(blank=True, max_length=300)),
                ("category", models.CharField(blank=True, max_length=400)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("pincode", models.CharField(blank=True, max_length=12)),
                (
                    "estimated_value_inr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "emd_inr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_high_value", models.BooleanField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("opening_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("awarded", "Awarded"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("detail_url", models.URLField(blank=True, max_length=2000)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenders",
                        to="tenders.buyer",
                    ),
                ),
            ],
            options={
                "ordering": ["deadline_at", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("source_key", models.CharField(max_length=200)),
                ("awardee_name", models.CharField(max_length=400)),
                ("awardee_normalised", models.CharField(max_length=400)),
                (
                    "awarded_value_inr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("awarded_at", models.DateTimeField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("detail_url", models.URLField(blank=True, max_length=2000)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards",
                        to="tenders.buyer",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards",
                        to="tenders.tender",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tender",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="tender_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(fields=["deadline_at"], name="tender_deadline_idx"),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(fields=["published_at"], name="tender_published_idx"),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(fields=["state"], name="tender_state_idx"),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(fields=["category"], name="tender_category_idx"),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["source", "published_at"], name="tender_source_published_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tender",
            constraint=models.UniqueConstraint(
                fields=("source", "source_key"), name="uniq_tender_source_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="tender",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_value_inr__gte", 0),
                    ("estimated_value_inr__isnull", True),
                    _connector="OR",
                ),
                name="tender_value_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="tender",
            constraint=models.CheckConstraint(
                condition=models.Q(("emd_inr__gte", 0), ("emd_inr__isnull", True), _connector="OR"),
                name="tender_emd_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="award",
            index=models.Index(fields=["awardee_normalised"], name="award_awardee_idx"),
        ),
        migrations.AddIndex(
            model_name="award",
            index=models.Index(fields=["awarded_at"], name="award_awarded_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="award",
            constraint=models.UniqueConstraint(
                fields=("source", "source_key"), name="uniq_award_source_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="award",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("awarded_value_inr__gte", 0),
                    ("awarded_value_inr__isnull", True),
                    _connector="OR",
                ),
                name="award_value_nonnegative",
            ),
        ),
    ]
